"""Add web playground starter code

Revision ID: 253b46af168c
Revises: 591665050cb0
Create Date: 2026-08-07 21:07:17.867665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '253b46af168c'
down_revision: Union[str, Sequence[str], None] = '591665050cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problems', sa.Column('starter_html', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('starter_css', sa.Text(), nullable=True))
    op.add_column('problems', sa.Column('starter_js', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('problems', 'starter_js')
    op.drop_column('problems', 'starter_css')
    op.drop_column('problems', 'starter_html')
    # ### end Alembic commands ###
